<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <PropertyGroup>
    <MyReferencePath>$(NewAge)\DotNet\Libs\lib\$(Configuration)\$(TargetFramework)</MyReferencePath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="$(MyReferencePath)\JWCEssentials.net.dll" />
    <Reference Include="$(MyReferencePath)\CrystalCatalystLibrary.net.dll" />
    <Reference Include="$(MyReferencePath)\CrystalSkia.net.dll" />
    <Reference Include="$(MyReferencePath)\FluentCommandLine.dll" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="SkiaSharp" Version="[3.119.2,4.0.0)" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="[3.119.2,4.0.0)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClipFlow.Format\ClipFlow.Format.csproj" />
  </ItemGroup>
</Project>
